const express = require('express');
const router = express.Router();
const analyticsController = require('./analytics.controller');
const { protect } = require('../../middleware/auth');
const { restrictTo } = require('../../middleware/rbac');
const { ROLES } = require('../../config/constants');
const catchAsync = require('../../utils/catchAsync');
const Complaint = require('../complaints/complaint.model');
const AuditLog = require('../audit/auditLog.model');
const PDFDocument = require('pdfkit');

// All analytics require supervisor+ access
router.use(protect);
router.use(restrictTo(ROLES.SUPERVISOR, ROLES.DEPARTMENT_ADMIN, ROLES.SUPER_ADMIN));

router.get('/dashboard', analyticsController.getDashboardSummary);
router.get('/by-department', analyticsController.getComplaintsByDepartment);
router.get('/over-time', analyticsController.getComplaintsOverTime);
router.get('/resolution-time', analyticsController.getResolutionTime);
router.get('/categories', analyticsController.getCategoryBreakdown);
router.get('/sla', analyticsController.getSlaReport);
router.get('/employees', restrictTo(ROLES.DEPARTMENT_ADMIN, ROLES.SUPER_ADMIN), analyticsController.getEmployeeStats);

// ─── PDF Report Generator ─────────────────────────────────────────────────────
router.get('/report/pdf', catchAsync(async (req, res) => {
  const { month, year } = req.query;
  const now = new Date();
  const reportMonth = parseInt(month) || now.getMonth() + 1;
  const reportYear = parseInt(year) || now.getFullYear();

  const startDate = new Date(reportYear, reportMonth - 1, 1);
  const endDate = new Date(reportYear, reportMonth, 0, 23, 59, 59);

  const complaints = await Complaint.find({
    createdAt: { $gte: startDate, $lte: endDate },
    isArchived: false,
  })
    .populate('raisedBy', 'name employeeId department')
    .populate('assignedTo', 'name')
    .lean();

  await AuditLog.create({
    action: 'REPORT_GENERATED',
    performedBy: req.user._id,
    details: { month: reportMonth, year: reportYear, count: complaints.length },
  });

  // Build PDF
  const doc = new PDFDocument({ margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=VSP-Report-${reportYear}-${reportMonth}.pdf`);
  doc.pipe(res);

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('Vizag Steel Plant', { align: 'center' });
  doc.fontSize(14).font('Helvetica').text('Complaint Management System — Monthly Report', { align: 'center' });
  doc.fontSize(12).text(`Period: ${startDate.toDateString()} to ${endDate.toDateString()}`, { align: 'center' });
  doc.moveDown();

  // Summary stats
  const resolved = complaints.filter(c => ['resolved', 'verified', 'closed'].includes(c.status)).length;
  const slaBreached = complaints.filter(c => c.slaBreached).length;

  doc.fontSize(14).font('Helvetica-Bold').text('Summary');
  doc.fontSize(12).font('Helvetica');
  doc.text(`Total Complaints: ${complaints.length}`);
  doc.text(`Resolved: ${resolved} (${complaints.length ? Math.round(resolved / complaints.length * 100) : 0}%)`);
  doc.text(`SLA Breached: ${slaBreached}`);
  doc.text(`Generated by: ${req.user.name} on ${new Date().toLocaleString()}`);
  doc.moveDown();

  // Complaints table
  doc.fontSize(14).font('Helvetica-Bold').text('Complaint Details');
  doc.moveDown(0.5);

  complaints.forEach((c, i) => {
    doc.fontSize(11).font('Helvetica-Bold').text(`${i + 1}. ${c.complaintNumber} — ${c.title}`);
    doc.fontSize(10).font('Helvetica');
    doc.text(`   Status: ${c.status} | Category: ${c.category} | Priority: ${c.priority}`);
    doc.text(`   Raised by: ${c.raisedBy?.name} (${c.raisedBy?.employeeId}) | Dept: ${c.assignedDept}`);
    doc.text(`   Date: ${new Date(c.createdAt).toLocaleDateString()} | SLA Breached: ${c.slaBreached ? 'Yes' : 'No'}`);
    if (c.resolutionNote) doc.text(`   Resolution: ${c.resolutionNote}`);
    doc.moveDown(0.5);

    // Page break if needed
    if (doc.y > 700 && i < complaints.length - 1) doc.addPage();
  });

  doc.end();
}));

module.exports = router;
